title: TrueLine
description: TrueLine tracks your bowling ball with your iPhone and measures speed, hook, breakpoint, and entry angle.
plugins:
  - jekyll-relative-links
defaults:
  - scope:
      path: ""
    values:
      layout: default
